//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAgent.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConnectMeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConnectMeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVCAgent.Resources.ConnectMeResource", typeof(ConnectMeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -AgentLoggedOut..
        /// </summary>
        internal static string AgentLoggedOut {
            get {
                return ResourceManager.GetString("AgentLoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent not connected.
        /// </summary>
        internal static string AgentNotConnected {
            get {
                return ResourceManager.GetString("AgentNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AgentSetupWizard2.
        /// </summary>
        internal static string AgentSetupWizard2 {
            get {
                return ResourceManager.GetString("AgentSetupWizard2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields must be correct!.
        /// </summary>
        internal static string AllFieldsMustBeCorrect {
            get {
                return ResourceManager.GetString("AllFieldsMustBeCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to Login.
        /// </summary>
        internal static string ClickToLogin {
            get {
                return ResourceManager.GetString("ClickToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to Logout.
        /// </summary>
        internal static string ClickToLogout {
            get {
                return ResourceManager.GetString("ClickToLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        internal static string CloseBracket {
            get {
                return ResourceManager.GetString("CloseBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected To HUB..
        /// </summary>
        internal static string ConnectedToHUB {
            get {
                return ResourceManager.GetString("ConnectedToHUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifty characters only!.
        /// </summary>
        internal static string FiftyCharactersOnly {
            get {
                return ResourceManager.GetString("FiftyCharactersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For .
        /// </summary>
        internal static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ,CustomerId: .
        /// </summary>
        internal static string InfoCustomerId {
            get {
                return ResourceManager.GetString("InfoCustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ,ExtensionNo: .
        /// </summary>
        internal static string InfoExtensionNo {
            get {
                return ResourceManager.GetString("InfoExtensionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Connected Agent: .
        /// </summary>
        internal static string InfoSuccessfullyConnectedAgent {
            get {
                return ResourceManager.GetString("InfoSuccessfullyConnectedAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoked HubMethod ApiRequestUpdation(.
        /// </summary>
        internal static string InvokedHubMethodApiRequestUpdation {
            get {
                return ResourceManager.GetString("InvokedHubMethodApiRequestUpdation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged agent is disconnected.
        /// </summary>
        internal static string LoggedAgentIsDisconnected {
            get {
                return ResourceManager.GetString("LoggedAgentIsDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Logged Out at. .
        /// </summary>
        internal static string LoggedOutAt {
            get {
                return ResourceManager.GetString("LoggedOutAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent can&apos;t exit properly. Error: .
        /// </summary>
        internal static string LoggerAgentCannotExitProperlyError {
            get {
                return ResourceManager.GetString("LoggerAgentCannotExitProperlyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent faced error during logging out. Error: .
        /// </summary>
        internal static string LoggerAgentFacedErrorDuringLoggingOutError {
            get {
                return ResourceManager.GetString("LoggerAgentFacedErrorDuringLoggingOutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckRecordExistsOrNot method Error: .
        /// </summary>
        internal static string LoggerCheckRecordExistsOrNotMethodError {
            get {
                return ResourceManager.GetString("LoggerCheckRecordExistsOrNotMethodError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection task is faulted. Error: .
        /// </summary>
        internal static string LoggerConnectionTaskIsFaultedError {
            get {
                return ResourceManager.GetString("LoggerConnectionTaskIsFaultedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error at ConnectToHub. Error: .
        /// </summary>
        internal static string LoggerErrorAtConnectToHubError {
            get {
                return ResourceManager.GetString("LoggerErrorAtConnectToHubError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error at reading Agents credentials from config file. Error: .
        /// </summary>
        internal static string LoggerErrorAtReadingAgentsCredentialsFromConfigFileError {
            get {
                return ResourceManager.GetString("LoggerErrorAtReadingAgentsCredentialsFromConfigFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Method Error: .
        /// </summary>
        internal static string LoggerMainMethodError {
            get {
                return ResourceManager.GetString("LoggerMainMethodError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Login into the application to test connection. Error: .
        /// </summary>
        internal static string LoggerPleaseLoginIntoTheApplicationToTestConnectionError {
            get {
                return ResourceManager.GetString("LoggerPleaseLoginIntoTheApplicationToTestConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem at Agent Login. Error: .
        /// </summary>
        internal static string LoggerProblemAtAgentLoginError {
            get {
                return ResourceManager.GetString("LoggerProblemAtAgentLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem at Creating SpecificAgent. Error: .
        /// </summary>
        internal static string LoggerProblemAtCreatingSpecificAgentError {
            get {
                return ResourceManager.GetString("LoggerProblemAtCreatingSpecificAgentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem at LoginLogout context menu click. Error: .
        /// </summary>
        internal static string LoggerProblemAtLoginLogoutContextMenuClickError {
            get {
                return ResourceManager.GetString("LoggerProblemAtLoginLogoutContextMenuClickError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem at Push to unique client. Error: .
        /// </summary>
        internal static string LoggerProblemAtPushToUniqueClientError {
            get {
                return ResourceManager.GetString("LoggerProblemAtPushToUniqueClientError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem in Set_property_of_Notify. Error: .
        /// </summary>
        internal static string LoggerProblemInSetPropertyOfNotifyError {
            get {
                return ResourceManager.GetString("LoggerProblemInSetPropertyOfNotifyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem on clicking Stop App. Error: .
        /// </summary>
        internal static string LoggerProblemOnClickingStopAppError {
            get {
                return ResourceManager.GetString("LoggerProblemOnClickingStopAppError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem on closing Agent Credential Form. Error: .
        /// </summary>
        internal static string LoggerProblemOnClosingAgentCredentialFormError {
            get {
                return ResourceManager.GetString("LoggerProblemOnClosingAgentCredentialFormError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped Applcation at: .
        /// </summary>
        internal static string LoggerStoppedApplcationAt {
            get {
                return ResourceManager.GetString("LoggerStoppedApplcationAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum five numeric digits only!.
        /// </summary>
        internal static string MaximumFiveNumericDigitsOnly {
            get {
                return ResourceManager.GetString("MaximumFiveNumericDigitsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected!.
        /// </summary>
        internal static string NotConnectedMsg {
            get {
                return ResourceManager.GetString("NotConnectedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected To HUB..
        /// </summary>
        internal static string NotConnectedToHUB {
            get {
                return ResourceManager.GetString("NotConnectedToHUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One instance of application is already running!.
        /// </summary>
        internal static string OneInstanceAlreadyRunning {
            get {
                return ResourceManager.GetString("OneInstanceAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Login into the application to test connection..
        /// </summary>
        internal static string PleaseLoginIntoTheApplicationToTestConnection {
            get {
                return ResourceManager.GetString("PleaseLoginIntoTheApplicationToTestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide AgentName!.
        /// </summary>
        internal static string ProvideAgentName {
            get {
                return ResourceManager.GetString("ProvideAgentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----------------------------------------------.
        /// </summary>
        internal static string SeperationLine {
            get {
                return ResourceManager.GetString("SeperationLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully connected .
        /// </summary>
        internal static string SuccessfullyConnected {
            get {
                return ResourceManager.GetString("SuccessfullyConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully opened url .
        /// </summary>
        internal static string SuccessfullyOpenedUrl {
            get {
                return ResourceManager.GetString("SuccessfullyOpenedUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error opening the connection..
        /// </summary>
        internal static string ThereWasAnErrorOpeningTheConnection {
            get {
                return ResourceManager.GetString("ThereWasAnErrorOpeningTheConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome .
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  with server..
        /// </summary>
        internal static string WithServer {
            get {
                return ResourceManager.GetString("WithServer", resourceCulture);
            }
        }
    }
}
